name: integration

on:

  pull_request:
    branches: [ Dev , Main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Output student name
      run: echo Van Overberghe Davy
    
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
      
    - name: Build
      working-directory: ./src
      run: dotnet build --no-restore
      
    - name: Test
      working-directory: ./src
      run: dotnet test --no-build --verbosity normal
